version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  chromadb:
    image: chromadb-image
    ports:
      - "8000:8000"

  batch:
    build:
      context: .
      dockerfile: modules/batch_pipeline/Dockerfile.batch
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
    depends_on:
      - kafka
      - chromadb

  summary:
    build:
      context: .
      dockerfile: modules/summarization/Dockerfile.summary
    depends_on:
      - kafka
      - chromadb

  inference:
    build:
      context: .
      dockerfile: modules/inference_pipeline/Dockerfile.inference
    depends_on:
      - kafka
      - chromadb
