# Use a slim Python image
FROM python:3.11

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt
# Copy the Python module into the container
COPY main_gradio_copy.py ./main_gradio_copy.py

# download ollama
RUN curl -fsSL https://ollama.com/install.sh | sh
# Expose the necessary port (for Gradio UI)
COPY id_ed25519 /root/.ollama/id_ed25519
RUN chmod 600 /root/.ollama/id_ed25519


EXPOSE 7860 11434

# Run the inference script
CMD ollama serve & sleep 10 && ollama pull mosrihari/unsloth_finance_alpaca && python ./main_gradio_copy.py
#CMD ["python", "./main_gradio.py"]
