# Use a slim Python image
FROM python:3.11

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python module into the container
COPY main.py ./main.py
COPY kafka_events.py ./kafka_events.py
COPY summary.py ./summary.py

CMD ["python", "./main.py"]
