# Use a slim Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python module into the container
COPY main.py ./main.py

ENV ALPACA_API_KEY=${ALPACA_API_KEY}
ENV ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}

CMD ["python", "./main.py"]
